server:
  port: 7000
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000