zipkin:
  storage:
    type: mysql
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/zipkin?useSSL=false
      username: weiwxie1
      password: '{cipher}AQAvW23aPbZRfxf4TWI9zPREZWNFTcgr8jwZrAnRqs8WmtqkXh9byQznW3uvPNc2CUMQbN/MlfvsxV6o6laHyqs8NciJlcQ+B10sVaDGMbAQLCYpRq4w14Pdhm92hgpPfn2J0Voxxp30EV96nmS+18Bh6aez1LLz6IDUhHk3gDbYUuht8rbx43EHnebGpHvlMxMFxBEyDE33U7hvkX0JKMNbZsJ4Rd8dlUG8yZFU+55Cl9XD0ZRuhRRQFg2zVmuxY7e1yGUVIt/APdWPgHpbNnSNdSeWtniIayMzh6W6UDchjleMmCtQ/J/U/+0oPrXcIsbKKpN5l2AzT4OnkXt+UtwIUUmpHzntDQB4UXvm6nu10lxyL+dAK+zNR61fwnaQK6k='
      max-active: 10
#      host: localhost
#      port: 3306
#      db: zipkin
#      use-ssl: false
server:
  compression:
    enabled: true
    min-response-size: 2048
#  port: 5000